### ISSUE TITLE
Error creating: pods "goldilocks-vpa-install-" is forbidden: error looking up service account default/goldilocks-vpa-install: serviceaccount "goldilocks-vpa-install" not found

### ISSUE THREAD

**Issue by rolfberkenbosch** [FairwindsOps/goldilocks#173] opened 2020-06-05 19:52 UTC
When using helm, i get the following error:

Error creating: pods "goldilocks-vpa-install-" is forbidden: error looking up service account default/goldilocks-vpa-install: serviceaccount "goldilocks-vpa-install" not found

**Comment by sudermanjr** [comment] 2020-06-08 16:13
This is a duplicate of the issue in charts https://github.com/FairwindsOps/charts/issues/306

**Closed by sudermanjr** 2020-06-08 16:13 UTC
