### ISSUE TITLE
Issue with Submit Button on Goldilocks Dashboard - CORS Error

### ISSUE THREAD

**Issue by Manjari4** [FairwindsOps/goldilocks#644] opened 2023-09-07 08:33 UTC
### What happened?

I encountered an issue while trying to use the submit button on the Goldilocks dashboard to add cost estimates. But the button was not working. 
Upon inspecting the console, I found the following error message:

![image](https://github.com/FairwindsOps/goldilocks/assets/98511353/3ee8b0d4-d5a4-4153-af0b-f54b54a8d1e5)
(i port-forwarded goldilocks on port:3333)

### What did you expect to happen?

The submit button should successfully add cost estimates to the Goldilocks dashboard without any CORS errors.

### How can we reproduce this?

Open the Goldilocks dashboard.
Click on the **Add cost estimates to your Goldilocks dashboard**'s Submit button.
Observe the error in the browser console.

### Version

v4.9.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment] 2023-09-07 16:39
Thanks for the report. I'll get someone to look at this. 

Note: I was able to reproduce both with a port-forward, and with an ingress fronting the object. This seems to be more likely an issue with our backend.

**Comment by sudermanjr** [comment] 2023-09-08 14:45
We believe we have identified the issue on our backend and are pushing out a fix soon. I will check back once it is live.

**Comment by sudermanjr** [comment] 2023-09-12 15:02
This should be fixed now. Thanks!

**Closed by sudermanjr** 2023-09-12 15:02 UTC
Labels: bug, triage

**Comment by Manjari4** [comment] 2023-09-18 05:22
thanks it's working fine now!
