### ISSUE TITLE
Support for Jobs

### ISSUE THREAD

**Issue by jeremywadsack** [FairwindsOps/goldilocks#100] opened 2019-12-12 19:07 UTC
As with #84 and #96 it would be really helpful for us to have support for pods created from Job resources. We use Jobs to run background workers that autoscale as the queues get loaded and clear. 

The workers are [generated based on queue hooks](https://github.com/keylimetoolbox/resque-kubernetes) and in our implementation have unique names for each job. So I'm looking for something more complicated that the current deployments which provide metrics based on the `metadata.name`. I'd like to aggregate resource recommendations based on jobs with the same `metadata.labels` values.

This might not be possible at this time, because it doesn't look like the [Job resource](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#job-v1-batch) has a Scale subresource as [required for the `targetRef`](https://cloud.google.com/kubernetes-engine/docs/concepts/verticalpodautoscaler#verticalpodautoscalerspec_v1_autoscalingk8sio).

Any thoughts on whether this is possible or other approaches to get this?

**Comment by sudermanjr** [comment] 2019-12-13 01:02
This is interesting. I haven't actually looked into how #84 and #96 will be implemented. Looking at the code for the VPA recommender, it seems that the targetRef in VPA can fetch jobs and cronjobs. https://github.com/kubernetes/autoscaler/blob/437353158dac1f13f3deb00c59be3cedad99bbc8/vertical-pod-autoscaler/pkg/target/fetcher.go#L82-L89

I will keep this in mind as we plan this work going forward. Thanks!

**Comment by jonkerj** [comment] 2020-02-11 08:38
Bump to freshen

**Comment by sudermanjr** [comment] 2020-09-15 15:28
closing in favor of #225

**Closed by sudermanjr** 2020-09-15 15:28 UTC
Labels: enhancement, pinned, stretch

**Comment by ilvez** [comment] 2023-06-22 09:47
@FrancoisPoinsot could you elaborate how to use this configuration exactly? This does not seem to be valid `values.yaml` if I'm looking at https://github.com/FairwindsOps/charts/blob/master/stable/goldilocks/values.yaml

**Comment by rnanudevops** [comment] 2024-01-24 13:41
Hi,

I am trying to implement Goldilocks with VPA using Helm and currently everything is working without problems, the problem is when I try to make the batch processes show up on the Goldilocks dashboard.
I have configured the dashboard-clusterrole by adding the following:

   - apiGroups:
       - 'batch'
     resources:
       - 'cronjobs'
       - 'jobs'
     verbs:
       - 'get'
       - 'list'
       - 'watch'
       
In this way I have managed to view the batch processes through the dashboard but it does not show any recommendations and within the cluster I do see the vpa generated and the corresponding recommendations.
Is there a way to configure this?

Thanks!

**Comment by ShayBenyo** [comment] 2025-07-28 08:28
> Hi,
> 
> I am trying to implement Goldilocks with VPA using Helm and currently everything is working without problems, the problem is when I try to make the batch processes show up on the Goldilocks dashboard. I have configured the dashboard-clusterrole by adding the following:
> 
> ```
> 
>    - apiGroups:
>        - 'batch'
>      resources:
>        - 'cronjobs'
>        - 'jobs'
>      verbs:
>        - 'get'
>        - 'list'
>        - 'watch'
>        
> ```
> 
> In this way I have managed to view the batch processes through the dashboard but it does not show any recommendations and within the cluster I do see the vpa generated and the corresponding recommendations. Is there a way to configure this?
> 
> Thanks!

Has anyone managed to figure this out?
Thanks!
