### ISSUE TITLE
Dashboard empty after upgrade

### ISSUE THREAD

**Issue by unguiculus** [FairwindsOps/goldilocks#285] opened 2021-01-26 16:10 UTC
I just upgraded from 3.0.3 to 3.1.4 with the result that the dashboard does not display anything but the following message:

`No namespaces are labelled for use by Goldilocks. Try labelling one with kubectl label ns NAMESPACE_NAME goldilocks.fairwinds.com/enabled=true`

Our namespaces are not labeled. We start the controller with `--on-by-default=true`. With 3.0.3 I had the option to display all VPA resources. This seems no longer possible.

**Comment by sudermanjr** [comment] 2021-01-26 16:46
Duplicate of #236

**Closed by sudermanjr** 2021-01-26 16:46 UTC
